export type CuratedIcon = {
  token: string
  label: string
  tags: string[]
  useCases: Array<'presentation' | 'sales' | 'marketing' | 'product' | 'support' | 'analytics'>
}

/**
 * Curated monochrome icons for story/presentation style UI.
 * This keeps picks visually consistent and AI/manual selection predictable.
 */
export const CURATED_STORY_ICONS: CuratedIcon[] = [
  { token: 'lucide:rocket', label: 'Launch', tags: ['launch', 'go-live', 'start'], useCases: ['presentation', 'sales', 'product'] },
  { token: 'lucide:sparkles', label: 'Highlight', tags: ['highlight', 'new', 'special'], useCases: ['presentation', 'marketing'] },
  { token: 'lucide:target', label: 'Target', tags: ['goal', 'focus', 'objective'], useCases: ['presentation', 'sales'] },
  { token: 'lucide:crosshair', label: 'Precision', tags: ['precision', 'accuracy', 'focus'], useCases: ['presentation', 'analytics'] },
  { token: 'lucide:briefcase', label: 'Business', tags: ['business', 'b2b', 'work'], useCases: ['sales', 'presentation'] },
  { token: 'lucide:building-2', label: 'Enterprise', tags: ['enterprise', 'org', 'company'], useCases: ['sales', 'presentation'] },
  { token: 'lucide:users', label: 'Audience', tags: ['users', 'team', 'people'], useCases: ['presentation', 'marketing', 'support'] },
  { token: 'lucide:user-round-check', label: 'Qualified Lead', tags: ['lead', 'qualified', 'customer'], useCases: ['sales', 'marketing'] },
  { token: 'lucide:handshake', label: 'Partnership', tags: ['partner', 'trust', 'deal'], useCases: ['sales', 'presentation'] },
  { token: 'lucide:message-square', label: 'Conversation', tags: ['chat', 'message', 'discussion'], useCases: ['sales', 'support'] },
  { token: 'lucide:mail', label: 'Email', tags: ['email', 'newsletter', 'contact'], useCases: ['marketing', 'sales'] },
  { token: 'lucide:phone', label: 'Call', tags: ['phone', 'call', 'connect'], useCases: ['sales', 'support'] },
  { token: 'lucide:calendar-days', label: 'Schedule', tags: ['calendar', 'timeline', 'plan'], useCases: ['presentation', 'sales', 'product'] },
  { token: 'lucide:clock-3', label: 'Time', tags: ['time', 'deadline', 'duration'], useCases: ['presentation', 'product'] },
  { token: 'lucide:timer', label: 'Speed', tags: ['speed', 'fast', 'time'], useCases: ['presentation', 'analytics'] },
  { token: 'lucide:gauge', label: 'Performance', tags: ['performance', 'velocity', 'metric'], useCases: ['analytics', 'product'] },
  { token: 'lucide:activity', label: 'Activity', tags: ['activity', 'signal', 'trend'], useCases: ['analytics', 'product'] },
  { token: 'lucide:trending-up', label: 'Growth Up', tags: ['growth', 'up', 'improvement'], useCases: ['analytics', 'sales', 'marketing'] },
  { token: 'lucide:trending-down', label: 'Risk Down', tags: ['risk', 'down', 'decline'], useCases: ['analytics', 'presentation'] },
  { token: 'lucide:chart-column', label: 'Bar Chart', tags: ['chart', 'bar', 'stats'], useCases: ['analytics', 'presentation'] },
  { token: 'lucide:chart-line', label: 'Line Chart', tags: ['chart', 'line', 'trend'], useCases: ['analytics', 'presentation'] },
  { token: 'lucide:chart-pie', label: 'Pie Chart', tags: ['chart', 'pie', 'breakdown'], useCases: ['analytics', 'presentation'] },
  { token: 'lucide:database', label: 'Data', tags: ['data', 'storage', 'system'], useCases: ['product', 'analytics'] },
  { token: 'lucide:server', label: 'Infrastructure', tags: ['infra', 'server', 'backend'], useCases: ['product', 'presentation'] },
  { token: 'lucide:layers-3', label: 'Architecture', tags: ['layers', 'stack', 'architecture'], useCases: ['product', 'presentation'] },
  { token: 'lucide:workflow', label: 'Workflow', tags: ['flow', 'process', 'automation'], useCases: ['product', 'support'] },
  { token: 'lucide:git-branch', label: 'Branching', tags: ['engineering', 'branch', 'decision'], useCases: ['product', 'presentation'] },
  { token: 'lucide:puzzle', label: 'Integration', tags: ['integration', 'plug', 'modular'], useCases: ['product', 'sales'] },
  { token: 'lucide:settings-2', label: 'Configuration', tags: ['settings', 'configuration', 'custom'], useCases: ['product', 'support'] },
  { token: 'lucide:wrench', label: 'Implementation', tags: ['build', 'implementation', 'fix'], useCases: ['product', 'support'] },
  { token: 'lucide:shield-check', label: 'Secure', tags: ['secure', 'compliance', 'trust'], useCases: ['sales', 'product'] },
  { token: 'lucide:shield-alert', label: 'Risk', tags: ['risk', 'warning', 'security'], useCases: ['presentation', 'product'] },
  { token: 'lucide:lock', label: 'Private', tags: ['lock', 'private', 'protected'], useCases: ['product', 'sales'] },
  { token: 'lucide:key-round', label: 'Access', tags: ['access', 'auth', 'key'], useCases: ['product', 'support'] },
  { token: 'lucide:badge-check', label: 'Verified', tags: ['verified', 'certified', 'proof'], useCases: ['sales', 'presentation'] },
  { token: 'lucide:triangle-alert', label: 'Warning', tags: ['warning', 'issue', 'attention'], useCases: ['presentation', 'support'] },
  { token: 'lucide:circle-alert', label: 'Critical', tags: ['critical', 'alert', 'urgent'], useCases: ['support', 'presentation'] },
  { token: 'lucide:circle-check-big', label: 'Success', tags: ['success', 'done', 'complete'], useCases: ['presentation', 'sales'] },
  { token: 'lucide:circle-x', label: 'Failure', tags: ['failure', 'error', 'no'], useCases: ['presentation', 'support'] },
  { token: 'lucide:zap', label: 'Fast', tags: ['speed', 'automation', 'power'], useCases: ['product', 'marketing'] },
  { token: 'lucide:lightbulb', label: 'Idea', tags: ['idea', 'insight', 'strategy'], useCases: ['presentation', 'marketing'] },
  { token: 'lucide:brain', label: 'Strategy', tags: ['strategy', 'thinking', 'planning'], useCases: ['presentation', 'sales'] },
  { token: 'lucide:compass', label: 'Direction', tags: ['direction', 'roadmap', 'navigation'], useCases: ['presentation', 'product'] },
  { token: 'lucide:map', label: 'Roadmap', tags: ['roadmap', 'journey', 'plan'], useCases: ['presentation', 'product'] },
  { token: 'lucide:flag', label: 'Milestone', tags: ['milestone', 'goal', 'checkpoint'], useCases: ['presentation', 'product'] },
  { token: 'lucide:milestone', label: 'Progress Marker', tags: ['progress', 'stage', 'milestone'], useCases: ['presentation', 'product'] },
  { token: 'lucide:arrow-right', label: 'Next Step', tags: ['next', 'continue', 'cta'], useCases: ['sales', 'marketing', 'support'] },
  { token: 'lucide:arrow-up-right', label: 'External Link', tags: ['link', 'open', 'external'], useCases: ['sales', 'marketing'] },
  { token: 'lucide:send', label: 'Submit', tags: ['send', 'submit', 'action'], useCases: ['sales', 'support', 'marketing'] },
  { token: 'lucide:mouse-pointer-click', label: 'Click Action', tags: ['click', 'action', 'convert'], useCases: ['marketing', 'sales'] },
  { token: 'lucide:megaphone', label: 'Announcement', tags: ['announcement', 'broadcast', 'campaign'], useCases: ['marketing', 'presentation'] },
  { token: 'lucide:bookmark', label: 'Save', tags: ['save', 'bookmark', 'remember'], useCases: ['product', 'support'] },
  { token: 'lucide:file-text', label: 'Document', tags: ['doc', 'report', 'content'], useCases: ['presentation', 'support'] },
  { token: 'lucide:book-open', label: 'Guide', tags: ['guide', 'education', 'learn'], useCases: ['support', 'marketing'] },
  { token: 'lucide:graduation-cap', label: 'Enablement', tags: ['training', 'enablement', 'learning'], useCases: ['support', 'sales'] },
  { token: 'lucide:dollar-sign', label: 'Revenue', tags: ['revenue', 'money', 'roi'], useCases: ['sales', 'analytics'] },
  { token: 'lucide:wallet', label: 'Budget', tags: ['budget', 'cost', 'finance'], useCases: ['sales', 'analytics'] },
  { token: 'lucide:receipt', label: 'Spend', tags: ['spend', 'invoice', 'cost'], useCases: ['analytics', 'presentation'] },
  { token: 'lucide:shopping-cart', label: 'Commerce', tags: ['commerce', 'cart', 'purchase'], useCases: ['marketing', 'sales'] },
  { token: 'lucide:truck', label: 'Delivery', tags: ['delivery', 'ship', 'fulfillment'], useCases: ['product', 'support'] },
  { token: 'lucide:globe', label: 'Global', tags: ['global', 'world', 'scale'], useCases: ['presentation', 'marketing'] },
  { token: 'lucide:map-pin', label: 'Location', tags: ['location', 'region', 'territory'], useCases: ['sales', 'support'] },
  { token: 'lucide:network', label: 'Connected Systems', tags: ['network', 'systems', 'platform'], useCases: ['product', 'presentation'] },
  { token: 'lucide:link-2', label: 'Connected', tags: ['link', 'connected', 'integration'], useCases: ['product', 'support'] },
]
